// 所有物品定义
export const ITEM_TYPES = {
  knife: {
    id: 'knife',
    name: '匕首',
    description: '锋利的匕首，可以防身，也可以切割',
    icon: '🔪',
    stackable: false,
    usable: true,
    useType: 'weapon',
    damage: 15,
    range: 3,
    consumeOnUse: false,
  },
  pistol: {
    id: 'pistol',
    name: '手枪',
    description: '有限的弹药，谨慎使用',
    icon: '🔫',
    stackable: false,
    usable: true,
    useType: 'weapon',
    damage: 35,
    range: 40,
    maxAmmo: 12,
    consumeOnUse: false,
  },
  diary: {
    id: 'diary',
    name: '日记本',
    description: '记录你每天的经历',
    icon: '📔',
    stackable: false,
    usable: true,
    useType: 'tool',
    action: 'openDiary',
    consumeOnUse: false,
  },
  cup: {
    id: 'cup',
    name: '杯子',
    description: '用来喝热水保暖',
    icon: '☕',
    stackable: false,
    usable: true,
    useType: 'consumable',
    requireItem: 'hotWater',
    effect: { temperature: 25 },
    consumeOnUse: false,
    consumeItem: 'hotWater',
  },
  kettle: {
    id: 'kettle',
    name: '烧水壶',
    description: '放在火堆旁可以烧热水',
    icon: '🫖',
    stackable: false,
    usable: false,
    useType: 'station',
  },
  campfireTool: {
    id: 'campfireTool',
    name: '烹饪工具',
    description: '用来烤肉和煮汤',
    icon: '🍳',
    stackable: false,
    usable: false,
    useType: 'station',
  },
  axe: {
    id: 'axe',
    name: '伐木工具',
    description: '砍树获取木材，也可以当武器',
    icon: '🪓',
    stackable: false,
    usable: true,
    useType: 'weapon',
    damage: 20,
    range: 4,
    consumeOnUse: false,
  },
  sleepingBag: {
    id: 'sleepingBag',
    name: '睡袋',
    description: '睡觉恢复体力，从夜晚跳到白天',
    icon: '🛏️',
    stackable: false,
    usable: false,
    useType: 'station',
  },
  wood: {
    id: 'wood',
    name: '木材',
    description: '砍树获得的木材，可做燃料',
    icon: '🪵',
    stackable: true,
    maxStack: 20,
    usable: true,
    useType: 'fuel',
    consumeOnUse: true,
  },
  rawMeat: {
    id: 'rawMeat',
    name: '生肉',
    description: '打猎获得的生肉，需要烹饪',
    icon: '🥩',
    stackable: true,
    maxStack: 10,
    usable: false,
  },
  cookedMeat: {
    id: 'cookedMeat',
    name: '烤肉',
    description: '恢复饥饿值',
    icon: '🍖',
    stackable: true,
    maxStack: 10,
    usable: true,
    useType: 'consumable',
    effect: { hunger: 30 },
    consumeOnUse: true,
  },
  soup: {
    id: 'soup',
    name: '热汤',
    description: '同时恢复饥饿和体温',
    icon: '🥣',
    stackable: true,
    maxStack: 5,
    usable: true,
    useType: 'consumable',
    effect: { hunger: 20, temperature: 15 },
    consumeOnUse: true,
  },
  hotWater: {
    id: 'hotWater',
    name: '热水',
    description: '烧开的水，可以喝',
    icon: '♨️',
    stackable: true,
    maxStack: 3,
    usable: true,
    useType: 'consumable',
    effect: { temperature: 20 },
    consumeOnUse: true,
  },
  animalSkin: {
    id: 'animalSkin',
    name: '动物皮',
    description: '可以用来保暖',
    icon: '🟤',
    stackable: true,
    maxStack: 10,
    usable: true,
    useType: 'consumable',
    effect: { temperature: 10 },
    consumeOnUse: true,
  },
  predecessorNote: {
    id: 'predecessorNote',
    name: '前辈笔记',
    description: '泛黄的纸页，上面写满了潦草的字迹',
    icon: '📄',
    stackable: false,
    usable: true,
    useType: 'tool',
    action: 'readNote',
    consumeOnUse: false,
  },
  forestMap: {
    id: 'forestMap',
    name: '森林地图',
    description: '标注了几个特殊位置的地图',
    icon: '🗺️',
    stackable: false,
    usable: true,
    useType: 'tool',
    action: 'readMap',
    consumeOnUse: false,
  },
};
